sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libconfig++-dev

language: cpp

compiler:
  - gcc

before_script:
  - ./autogen.sh

script:
  - ./configure
  - make

notifications:
  on_success: never
  on_failure: never
