#!/bin/sh

### BEGIN INIT INFO
# Provides:          dominus
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Dominus main server
# Description:       Start Dominus main server
### END INIT INFO

# Author: Noelie Ramuzat & Rémi Rigal

case $1 in
    start)
        echo "Starting Dominus Server..."
        modprobe i2c-dev
        modprobe i2c-bcm2835
        LD_LIBRARY_PATH=/usr/lib/dominus dominus-server -c /etc/dominus.cfg & > /dev/null 2>&1
        echo "Dominus Server started"
    ;;

    *)
        echo "Usage: /etc/init.d/dominus start"
        exit 1
    ;;
esac

exit 0
